// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wyjocbqbdyqecyrmbjyw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind5am9jYnFiZHlxZWN5cm1ianl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2NjI4MDYsImV4cCI6MjA2OTIzODgwNn0.uYwWyVESbQlgI5TTogV9UosF6rYu_X311F-O1k_umME";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});